server:
  port: 8888

logging:
  dir: log
  config: classpath:config/logback.xml
  instance:
    dir: log/intance_log
    pattern: /job_id_%s/instance_id_%s.log

spring:
  jackson:
    mapper:
      propagate-transient-marker: true
  thymeleaf:
    prefix: "classpath:/static/"
  datasource:
    url: jdbc:mysql://localhost:3306/flinkplus?serverTimezone=Asia/Shanghai&?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.ddcoding.flinkplus.dao.conf.DataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000t

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.ddcoding.flinkplus.model
  configLocation: classpath:config/mybatis-config.xml


#热部署组件
devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 8666
  restart:
    enabled: true #是否支持热部署

kerberos:
  keytab:
  principal:

#'yarn' or 'standalone'
cluster:
  mode: yarn